// <auto-generated />
using FoodReview.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodReview.Solution.Migrations
{
    [DbContext(typeof(FoodReviewContext))]
    [Migration("20211026190028_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("FoodReview.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FoodGroup")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageLocation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasMaxLength(10000)
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            FoodGroup = "Dairy",
                            ImageLocation = "https://www.refinery29.com/images/10001972.jpg?crop=40%3A21",
                            ImageName = "glass of milk",
                            Name = "Milk",
                            Rating = 2,
                            Review = "It's good in coffee."
                        },
                        new
                        {
                            FoodId = 2,
                            FoodGroup = "Meat",
                            ImageLocation = "https://d1nqx6es26drid.cloudfront.net/app/uploads/2015/04/04043817/product-hamburger.png",
                            ImageName = "hamburger",
                            Name = "Hamburger",
                            Rating = 3,
                            Review = "This is a good standard food, when you're hungry. It'll fill you up."
                        },
                        new
                        {
                            FoodId = 3,
                            FoodGroup = "Dinner",
                            ImageLocation = "https://www.istockphoto.com/photo/cheesy-pepperoni-pizza-gm938742222-256696208",
                            ImageName = "Slice of Pizza",
                            Name = "Pizza",
                            Rating = 5,
                            Review = "This food needs no review because it's the only food that actually matters. Grab a slice, kick back, and relish in the fact that you just took a bite out of heaven."
                        },
                        new
                        {
                            FoodId = 4,
                            FoodGroup = "Vegetables",
                            ImageLocation = "https://images.indianexpress.com/2019/12/Peas_759.jpg",
                            ImageName = "Peas",
                            Name = "Peas",
                            Rating = 1,
                            Review = "These little nightmare balls serve no purpose other than to ruin the rest of your meal by tainting your palate."
                        },
                        new
                        {
                            FoodId = 5,
                            FoodGroup = "Vegetable",
                            ImageLocation = "https://www.freshpoint.com/wp-content/uploads/commodity-carrot.jpg",
                            ImageName = "carrots",
                            Name = "Carrot",
                            Rating = 5,
                            Review = "Crunchy. Orange. Snowman noses. What more do you want?"
                        },
                        new
                        {
                            FoodId = 6,
                            FoodGroup = "Breakfast",
                            ImageLocation = "https://4eojie3jgd8h1h57zz1bwc39-wpengine.netdna-ssl.com/wp-content/uploads/2018/12/PurelyOs_Main_1028.png",
                            ImageName = "breakfast cereal",
                            Name = "Breakfast Cereal",
                            Rating = 3,
                            Review = "Depends."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
