// <auto-generated />
using FoodReview.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodReview.Solution.Migrations
{
    [DbContext(typeof(FoodReviewContext))]
    [Migration("20211027222235_MoreSeeds")]
    partial class MoreSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("FoodReview.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Name = "Milk"
                        },
                        new
                        {
                            FoodId = 2,
                            Name = "Bread"
                        },
                        new
                        {
                            FoodId = 3,
                            Name = "Eggs"
                        },
                        new
                        {
                            FoodId = 4,
                            Name = "Breakfast Cereal"
                        });
                });

            modelBuilder.Entity("FoodReview.Models.FoodGroup", b =>
                {
                    b.Property<int>("FoodGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FgName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("FoodGroupId");

                    b.ToTable("FoodGroup");

                    b.HasData(
                        new
                        {
                            FoodGroupId = 1,
                            FgName = "Dairy"
                        },
                        new
                        {
                            FoodGroupId = 2,
                            FgName = "Grain"
                        },
                        new
                        {
                            FoodGroupId = 3,
                            FgName = "Protein"
                        });
                });

            modelBuilder.Entity("FoodReview.Models.FoodRating", b =>
                {
                    b.Property<int>("FoodRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("FoodRatingId");

                    b.HasIndex("FoodId");

                    b.HasIndex("RatingId");

                    b.ToTable("FoodRating");

                    b.HasData(
                        new
                        {
                            FoodRatingId = 1,
                            FoodId = 1,
                            RatingId = 1
                        },
                        new
                        {
                            FoodRatingId = 2,
                            FoodId = 2,
                            RatingId = 2
                        },
                        new
                        {
                            FoodRatingId = 3,
                            FoodId = 3,
                            RatingId = 3
                        },
                        new
                        {
                            FoodRatingId = 4,
                            FoodId = 4,
                            RatingId = 4
                        });
                });

            modelBuilder.Entity("FoodReview.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ImageId");

                    b.HasIndex("FoodId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            FoodId = 1,
                            ImageLocation = "https://www.refinery29.com/images/10001972.jpg?crop=40%3A21",
                            ImageName = "glass of milk"
                        },
                        new
                        {
                            ImageId = 2,
                            FoodId = 2,
                            ImageLocation = "https://unsplash.com/photos/e83dQJ-BMog",
                            ImageName = "bread"
                        },
                        new
                        {
                            ImageId = 3,
                            FoodId = 3,
                            ImageLocation = "https://www.simplyrecipes.com/thmb/akJysvaQmkQpLt7Q2_SfA_jr2PU=/800x533/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2014__07__hard-boiled-eggs-horiz-800-429f7e9948b84a6d84237e228f9d54f2.jpg",
                            ImageName = "eggs"
                        },
                        new
                        {
                            ImageId = 4,
                            FoodId = 4,
                            ImageLocation = "https://images.unsplash.com/photo-1578831914933-6339766eb29b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80",
                            ImageName = "b in cereal"
                        });
                });

            modelBuilder.Entity("FoodReview.Models.Pyramid", b =>
                {
                    b.Property<int>("PyramidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FoodGroupId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("PyramidId");

                    b.HasIndex("FoodGroupId");

                    b.HasIndex("FoodId");

                    b.ToTable("Pyramid");

                    b.HasData(
                        new
                        {
                            PyramidId = 1,
                            FoodGroupId = 1,
                            FoodId = 1
                        },
                        new
                        {
                            PyramidId = 2,
                            FoodGroupId = 2,
                            FoodId = 2
                        },
                        new
                        {
                            PyramidId = 3,
                            FoodGroupId = 3,
                            FoodId = 3
                        },
                        new
                        {
                            PyramidId = 4,
                            FoodGroupId = 2,
                            FoodId = 4
                        });
                });

            modelBuilder.Entity("FoodReview.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.ToTable("Rating");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            Stars = 3
                        },
                        new
                        {
                            RatingId = 2,
                            Stars = 5
                        },
                        new
                        {
                            RatingId = 3,
                            Stars = 5
                        },
                        new
                        {
                            RatingId = 4,
                            Stars = 2
                        });
                });

            modelBuilder.Entity("FoodReview.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ReviewId");

                    b.HasIndex("FoodId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            FoodId = 1,
                            ReviewText = "It's good in coffee."
                        },
                        new
                        {
                            ReviewId = 2,
                            FoodId = 2,
                            ReviewText = "There is not a thing that is more positive than bread. - Fyodor Dostoevsky"
                        },
                        new
                        {
                            ReviewId = 3,
                            FoodId = 3,
                            ReviewText = "Eggs are the best."
                        },
                        new
                        {
                            ReviewId = 4,
                            FoodId = 4,
                            ReviewText = "It depends."
                        });
                });

            modelBuilder.Entity("FoodReview.Models.FoodRating", b =>
                {
                    b.HasOne("FoodReview.Models.Food", "Food")
                        .WithMany("JoinEntities")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodReview.Models.Rating", "Rating")
                        .WithMany("JoinEntities")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("FoodReview.Models.Image", b =>
                {
                    b.HasOne("FoodReview.Models.Food", "Food")
                        .WithMany("Images")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FoodReview.Models.Pyramid", b =>
                {
                    b.HasOne("FoodReview.Models.FoodGroup", "FoodGroup")
                        .WithMany("JoinEntities2")
                        .HasForeignKey("FoodGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodReview.Models.Food", "Food")
                        .WithMany("JoinEntities2")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("FoodGroup");
                });

            modelBuilder.Entity("FoodReview.Models.Review", b =>
                {
                    b.HasOne("FoodReview.Models.Food", "Food")
                        .WithMany("Reviews")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FoodReview.Models.Food", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("JoinEntities");

                    b.Navigation("JoinEntities2");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FoodReview.Models.FoodGroup", b =>
                {
                    b.Navigation("JoinEntities2");
                });

            modelBuilder.Entity("FoodReview.Models.Rating", b =>
                {
                    b.Navigation("JoinEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
